steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "./"
      - "-t"
      - "us.gcr.io/dev-trials-q/gke-job-trigger-job1:v0.0"
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "us.gcr.io/dev-trials-q/gke-job-trigger-job1:v0.0"