steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "./"
      - "-t"
      - "us.gcr.io/dev-trials-q/job-controller:v0.7"
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "us.gcr.io/dev-trials-q/job-controller:v0.7"