apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: job-controller
  name: job-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: job-controller
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: job-controller
      name: job-controller
    spec:
      containers:
        - name: controller
          image: us.gcr.io/dev-trials-q/job-controller:v0.7
          ports:
            - containerPort: 5000
          env:
            - name: HOST_URL
              value: "https://35.193.124.71"
            - name: CACERT
              value: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURLakNDQWhLZ0F3SUJBZ0lRQTVwVmxQZG9tVXVyVUhOT3VlSUR1ekFOQmdrcWhraUc5dzBCQVFzRkFEQXYKTVMwd0t3WURWUVFERXlRMFltWTRabU5sTmkwek0yVTBMVFF6WWpBdFltUTBOQzA1T1dNeVpqSXhOREptWlRZdwpIaGNOTWpFd01qQTVNRFV5TXpBM1doY05Nall3TWpBNE1EWXlNekEzV2pBdk1TMHdLd1lEVlFRREV5UTBZbVk0ClptTmxOaTB6TTJVMExUUXpZakF0WW1RME5DMDVPV015WmpJeE5ESm1aVFl3Z2dFaU1BMEdDU3FHU0liM0RRRUIKQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUUQrSFMzUVgvK095YXZJK1o4T1VzRHQxbFJzMnFxL3pVSDNXMFJhaGh4QwpqUGpNWGtFbFZXRFpMaWp5SS9rRWtaSjAzdUZyZlBsZnMvNWxRNnhCVTlzdXU3dEt3dFg0ZWVvamw5aElTWVh1Cjg0WWV3RGpZMUQ3SDN4R25yelRnemczNWpiQUhEYkJvbFoxUlk0R2JtS2d0M2wyYnNabzkwUm1aelNJNWdMSlgKbE9aZUl0STgrbWwwaGl0U1lmdDRLZkN5NXVvbytoajM4T3l4VisydXZSNkYrZHE5NE1IcG12b1UwcTlWcmF1RQpPZHN1L0ErMmd0bnJ5QWFrSTJnMlBHbDNla1EyTWV2eG5KODFEMEJKU2Rnc0s4STFnN0EzN05wNFRMVWZ0QUJKClhVbHVkd1pTcDIxUE1IWkRBZk5pbE1oeFVhTWw2Z0tXekhRdmlpSUNOamNiQWdNQkFBR2pRakJBTUE0R0ExVWQKRHdFQi93UUVBd0lDQkRBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJUMjB4QmtmQlU1NENJago0dUJkcThWWnVPVEdhVEFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBbUVsREpHSlg0aUQxYVdNS1RsdG90cnduClZzQzk0MmxndHlxWDNyKzBKZWdDWlVtRmdmRUkraEs2RGUrS1lNaDFZRG1mOURZb1cxckN3R0hIZ2dwcnp2QVoKdm41TC8rWnlDVkd5Z216bnd1UnpPbW1ac0p0SjhzV2lhV0pDNVU3T3Yrb3I3Z1JneHJvM3YydEFaNmNNU2NTSQpLVkx6VGx6bW92b01LQUxVR1F2MzJvR0IxL0txZTVoVUd5NUZtN0ZpeWtObDF2VzhTZE8wZWo5eGJGUk1FTFRSCnJDamhmQThnTGFGZ0lYM2laYzJUWUZadmtjdWZ3RXV3SXN2RlR2cThjNEl0UnJIc3lCb3BOZzkxNGdpQ0dJZ0cKd1JZdGhVRExVTHdxSDVWWVpDdlo2VW9IWGppd2NWam95QkxUdkI0b3NpMXJnV1Q5d0NwcEkvVUhZK2RKMmc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg=="
            - name: TOKEN
              value: "ZXlKaGJHY2lPaUpTVXpJMU5pSXNJbXRwWkNJNklsUlJMVVJPY2poaWRuaFZjMmxLUnpkTlNuSTFPVnA0ZWtWdmRrSmFlV2RyZGpKcFJTMUNjR1EzVVRBaWZRLmV5SnBjM01pT2lKcmRXSmxjbTVsZEdWekwzTmxjblpwWTJWaFkyTnZkVzUwSWl3aWEzVmlaWEp1WlhSbGN5NXBieTl6WlhKMmFXTmxZV05qYjNWdWRDOXVZVzFsYzNCaFkyVWlPaUprWldaaGRXeDBJaXdpYTNWaVpYSnVaWFJsY3k1cGJ5OXpaWEoyYVdObFlXTmpiM1Z1ZEM5elpXTnlaWFF1Ym1GdFpTSTZJbXB2WWkxdFlXNWhaMlZ5TFhSdmEyVnVMV2R6ZW5weklpd2lhM1ZpWlhKdVpYUmxjeTVwYnk5elpYSjJhV05sWVdOamIzVnVkQzl6WlhKMmFXTmxMV0ZqWTI5MWJuUXVibUZ0WlNJNkltcHZZaTF0WVc1aFoyVnlJaXdpYTNWaVpYSnVaWFJsY3k1cGJ5OXpaWEoyYVdObFlXTmpiM1Z1ZEM5elpYSjJhV05sTFdGalkyOTFiblF1ZFdsa0lqb2lNamcwTkRGa1pUY3ROMlk1T1MwMFpqZG1MVGxsWmpNdFpUYzFNREptT0RFek1tWmtJaXdpYzNWaUlqb2ljM2x6ZEdWdE9uTmxjblpwWTJWaFkyTnZkVzUwT21SbFptRjFiSFE2YW05aUxXMWhibUZuWlhJaWZRLlgwWVFfdmMzLTZ1MGYzUzNUbUdZT2dUOVl2YlpOM1pGUkJQbzhtMXNIdUpJWEszT25lc18yUzQwZFN6NXZQQzhYamZvVHozRUM4V01vbVdBNUxOREd6NWxVV0NmRkhNS3ZMNVNtZUEzZzZBTm9ReVlNdXlUNnhXcEhsSFJsc3lXanlLdEZLV00tbDQxTmtrbXdhYjlMdXl4Sm15UzZwY2FkNlY4Z2pXZU1LQnE5NFBHajh6TzdyRy1zY0VzNlpndFJ2Mlk1TmhkLVFSc3ZRNmlLakdNWlRMS3BVSGlxQTFSazEwdGlMR1NKNnEzUXRRZWJtSUZRaDkyTmZXanBUdVRCVWR4UWhOY2xRckxGNzlBMjNZNk9HM1E0bWQ3UGo2LU5NdWFOZ3I1d0hvMDlrQVNtdzJISWxKcE02d2VNNlRPcXNtaHJuMUNKeVdyS3dTODhZSDI4UQ=="
          livenessProbe:
            httpGet:
              port: 5000
              path: /healthz
            initialDelaySeconds: 3
            periodSeconds: 5
          readinessProbe:
            httpGet:
              port: 5000
              path: /healthz
            initialDelaySeconds: 3
            periodSeconds: 5
