apiVersion: batch/v1
kind: Job
metadata:
  name: job2
spec:
  template:
    spec:
      containers:
      - name: job2
        image: us.gcr.io/dev-trials-q/gke-job-trigger-job2:v0.0
        env:
          - name: PROCESS_FOLDER
            value: "2021-2-9_5-51-48"
      restartPolicy: Never
  backoffLimit: 4