---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: job-manager
  namespace: default
rules:
- apiGroups:
  - "batch"
  resources:
  - jobs
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - pods
  - pods/log
  verbs:
  - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: job-manager
  namespace: default
subjects:
- kind: ServiceAccount
  name: job-manager
  namespace: default
roleRef:
  kind: Role
  name: job-manager
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: job-manager
  namespace: default